version: '3.1'
services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - "./:/var/www/html:z"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
  joomladb:
    image: mysql:5.6
    ports:
      - 32775:3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
      # - "./data/ycf_youthforward_2020-05-13.sql:/var/lib/mysql/ycf_youthforward_2020-05-13.sql"
    environment:
      MYSQL_ROOT_PASSWORD: example
